### ISSUE TITLE
Can't make browser sync reload page

### ISSUE THREAD

**Issue by rtvt** [retyui/prestashop-1.7-webpack-2-hot-module-replacement#1]
Hello,
1) CSS works perfect. 
2) TPL - I can't make page reload when I change .tpl file. I tried I think all possible path variations in the 

```
browserSync.init({
	open: true
	, port: bsPort
	, proxy: {
		target: `http://test.dev` //host your local webserver
	}
	, src: [`./templates/**/*.tpl`, `./modules/**/*.tpl`] // full page reload if .tpl file changed
```
I have classic theme stucture:
_dev
    - css
    - js
    - webpack here
assets
**templates**

so I tried `./templates/**/*.tpl , ../templates/**/*.tpl` and some different variants, but it's not reload page and do nothing.

3) JS - when I change something in theme.js file for example, I have webpack: Compiled successfully, but browsersync not reload page with this error in browser console:

```

process-update.js:95 [HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See https://webpack.js.org/concepts/hot-module-replacement/ for more details.
logUpdates @ process-update.js:95
process-update.js:103 [HMR]  - ./js/theme.js

"[HMR] The following modules couldn't be hot updated: " +
          "(Full reload needed)\n" +
          "This is usually because the modules which have changed " +
          "(and their parents) do not know how to hot reload themselves. " +
          "See " + hmrDocsUrl + " for more details."

```

Thank you in advance, your guide is great.

**Comment by retyui** [comment]
it is very strange, in my spare time I will check the webpack\browsersync

**Comment by retyui** [comment]
@rtvt Is my mistake (
(wrong paths)
try this code:
```js
browserSync.init({
	// ...
	src: [ // full page reload if .tpl file changed
		'../templates/**/*.tpl',
		'../modules/**/*.tpl'
	],
```

**Comment by rtvt** [comment]
thank you for answer. Paths are now correct, as I said I tried it already, but just nothing happens when I change something and save any .tpl file in both folders. No reaction in cmd or browser console. (meanwhile CSS change+save works perfect)

This part of my config:
```
browserSync.init({
	open: true
	, port: bsPort
	, proxy: {
		target: `http://test.dev` //host your local webserver
	}
	, src: [ // full page reload if .tpl file changed
		'../templates/**/*.tpl',
		'../modules/**/*.tpl'
	]
	, middleware: [
		webpackDevMiddleware( bundler, {
			// IMPORTANT: dev middleware can't access config, so we should
			// provide publicPath by ourselves
			publicPath: webpackConfig.output.publicPath
			, stats: { colors: true , chunck : false}
			, hot: true
		} ),
		webpackHotMiddleware( bundler )
	]
});
```

I'm fine with hand reloading after change .tpl and .js, cause 90% modifications are in CSS files, which works with HMR, but if we can find a solution it would be great.

**Comment by retyui** [comment]
Pls Change `src:` -> `files:`

**Comment by rtvt** [comment]
Great, it works. Thank you!

**Comment by retyui** [comment]
https://github.com/retyui/prestashop-1.7-webpack-2-hot-module-replacement/commit/aaadef23f893203d1e1d9f5aedd411c9856c2f5d
